# Général
spring.application.name=book_media_store

# Configuration MySQL
# 1. On remet le port 3306 pour MySQL
# 2. On vérifie que le mot de passe est bien 'root' (souvent vide sur XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/bookmediastore?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Port du serveur BACKEND (On remet 8080 pour éviter le conflit avec React)
server.port=8080

# Configuration pour le Frontend (React sur port 3000)
spring.application.frontend-url=http://localhost:3000

# Uploads
upload.path=uploads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
app.blog.image-upload-dir=uploads/blog-images

# Logs
logging.level.org.springframework.security=INFO